# Generated by Django 3.2.8 on 2023-01-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20230117_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='text',
        ),
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание сообщества'),
        ),
    ]
