# Generated by Django 3.2.8 on 2023-04-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_auto_20230412_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(through='post.TagPost', to='post.Tag'),
        ),
    ]
